# Copy this file as "config.yaml", and fill in the values as appropriate.
# ------------------------------------------------------------------------------

# Twitter API token
twitterBearerToken:

# How many nested quotes to reply with by default. -1 is infinite, 0 is bot is off
defaultDepth: 1

# Max nested quotes to reply with. -1 is infinite, 0 is bot is off
maxDepth: 3

quoteCache:
  # Cache TTL in seconds for Twitter ID/author lookups.
  ttl: 43200

  # Cache key max for Twitter ID/author lookups.
  maxKeys: 40
